# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'test_config',
        SOURCES = [ 'main.cc' ],
        INCLUDE = [ 'sigma0' ],
        OBJS    = [ '#service/simplemalloc.o', '#service/logging.o', '#service/vprintf.o'],
        MEMSIZE = 1<<20)

# EOF
