CC=avr-gcc
AR=avr-ar
NM=avr-avr
RANLIB=avr-ranlib

CFLAGS= -Os -Wall -mcall-prologues -mmcu=$(MCU) -DF_CPU=$(FREQ)UL

include Makefile.inc

CFLAGS+=-DUIP_CONF_IPV6=1
LIB=uip6

SRCS=$(UIP6_SRC) $(LIB_SRC)
OBJS= $(SRCS:.c=.o)
all: $(OBJS)
	$(AR) cr $(LIB).a $(OBJS)
	$(RANLIB) $(LIB).a

clean:
	@-rm *.o *.a
