CC=gcc
AR=ar
NM=nm
RANLIB=ranlib

CFLAGS= -g -Os -Wall

include Makefile.inc

CFLAGS+=-DUIP_CONF_IPV6=1
LIB=uip6

SRCS=$(UIP6_SRC) $(LIB_SRC)
ifneq ($(HAVE_6LOWPAN),)
SRCS+=$(6LOWPAN_SRC)
endif

OBJS= $(SRCS:.c=.o)

all: $(OBJS)
	$(AR) cr $(LIB).a $(OBJS)
	$(RANLIB) $(LIB).a

clean:
	@rm *.o *.a
