# -*- Mode: Python -*-

import nul
Import('target_env')
nul.Lib(target_env, 'model', SOURCES = filter(lambda x: x.name != 'qemu_net.cc', Glob('*.cc')))

qemu_env = target_env.Clone()
qemu_env.Append(CPPPATH = ["../contrib/qemu/src/", "../contrib/qemu/modified/"])
nul.Lib(target_env, 'qemunet', SOURCES = qemu_env.Object(["qemu_net.cc"] + "../contrib/qemu/modified/qemu.c ../contrib/qemu/src/hw/ne2000.c ../contrib/qemu/src/hw/e1000.c ../contrib/qemu/src/net-checksum.c".split()))
# EOF
