# -*- Mode: Python -*-

import nul
Import('target_env')

target_env.Append(CPPPATH = ['contrib/src/include', 'contrib/src/include/ipv4', 'contrib/src/include/ipv6',
                             'own/include', '../../../vancouver/include']);

nul.Lib(target_env, 'ip_lwip',
        SOURCES = [Glob('contrib/src/core/*.c'),
                   Glob('contrib/src/core/ipv4/*.c'),
                   Glob('contrib/src/api/*.c'),
                   Glob('contrib/src/api/ipv4/*.c'),
                   Glob('contrib/src/netif/*.c'),
                   'own/sys.cc'])
