# -*- Mode: Python -*-

import nul

Import('target_env')

nul.Lib(target_env,
        "tinf",
        SOURCES = [
        'src/tinflate.c',
        'src/tinfgzip.c',
        'src/tinfzlib.c',
        'src/adler32.c',
        'src/crc32.c',
        ])

# EOF
