# -*- Mode: Python -*-

import nul

Import('target_env')

nul.Lib(target_env,
        'hostnetwork',
        SOURCES = [ 'host82576.cc',
                    'simplebootp.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

nul.Lib(target_env,
        'hostsimple',
        SOURCES = [ 'hostio.cc',
                    'hostpcicfg.cc',
                    'hostkeyboard.cc',
                    'hostsink.cc',
                    'hostserial.cc',
                    'hostpit.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

nul.Lib(target_env,
        'hostdisk',
        SOURCES = [ 'hostide.cc',
                    'hostahci.cc',
                    'virtualdisk.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])


nul.Lib(target_env,
        'hostvesa',
        SOURCES = [ 'hostvesa.cc',
                    '../models/memorycontroller.o',
                    '../executor/novahalifax.o',
                    '../models/pit8254.o',
                    '../models/sysctrlport.o',
                    '../models/pcihostbridge.o',
                    '../models/pcidirect.o',
                    '../models/directio.o',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

def SimpleHost(name):
    return nul.Lib(target_env, name,
                   SOURCES = [ name + '.cc'],
                   INCLUDE = [ 'sigma0' ],
                   LIBS = ['runtime', 'string', 'nova'])

for n in ['hostvga', 'hostrtc']:
    SimpleHost(n)

# EOF
