# -*- Mode: Python -*-

import nul

Import('target_env')

#for f in Glob('*.cc'):
#    target_env.Object(f)

nul.Lib(target_env,
        'hostsimple',
        SOURCES = [ 'hostio.cc',
                    'hostpcicfg.cc',
                    'hostkeyboard.cc',
                    'hostsink.cc',
                    'hostserial.cc',
                    'hostpit.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

nul.Lib(target_env,
        'hostdisk',
        SOURCES = [ 'hostide.cc',
                    'hostahci.cc',
                    'virtualdisk.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])


nul.Lib(target_env,
        'hostvesa',
        SOURCES = [ 'hostvesa.cc',
                    '../models/memorycontroller.cc',
                    '../executor/novahalifax.cc',
                    '../models/pit8254.cc',
                    '../models/sysctrlport.cc',
                    '../models/pcihostbridge.cc',
                    '../models/pcidirect.cc',
                    '../models/directio.cc',
                    ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

def SimpleHost(name):
    return nul.Lib(target_env, name,
                   SOURCES = [ name + '.cc'],
                   INCLUDE = [ 'sigma0' ],
                   LIBS = ['runtime', 'string', 'nova'])

for n in ['hostvga', 'hostrtc']:
    SimpleHost(n)

# EOF
