# -*- Mode: Python -*-

Import('output_dir')
Import('target_env')

target_env.Link(output_dir + '/apps/rocknshine.nova',
                [ 'rocknshine.cc',
                  ],
                LIBS=['runtime', 'tinf'],
                linkscript="linker.ld")

# EOF
