# -*- Mode: Python -*-

import nul

Import('target_env')

nul.Lib(target_env, 'runtime',
        SOURCES = [
        'logging.cc',
        'simplemalloc.cc',
        'vprintf.cc',
        ],
        LIBS = ['string', 'nova'])

# EOF
