extern const char http_get[5];
extern const char http_content_type[15];
extern const char http_index_html[12];
extern const char http_404_html[10];
extern const char http_header_200[52];
extern const char http_header_404[59];
extern const char http_content_type_plain[29];
extern const char http_content_type_html[28];
extern const char http_content_type_xml [34];
extern const char http_content_type_binary[43];
extern const char http_html[6];
extern const char http_shtml[7];
extern const char http_sxml[6];
