# -*- Mode: Python -*-

import nul

Import('target_env')

nul.Lib(target_env,
        "runtime",
        SOURCES = [
        'cpp-support.cc',
        'string.cc',
        'capalloc.cc',
        # compiler-rt
        'udivdi3.S'
        ])

# EOF
