# -*- Mode: Python -*-

import nul

Import('target_env')
Import('host_env')

nul.App(target_env, 'rocknshine',
        SOURCES = [ 'rocknshine.cc' ],
        INCLUDE = [ 'sigma0' ],
        OBJS    = [ '#service/simplemalloc.o', '#service/logging.o', '#service/vprintf.o'],
        LIBS    = [ 'tinf'],
        MEMSIZE = 1<<16)

host_env.Command('#bin/apps/rocknshine.example', ['pdfprepare.py', 'presentation.pdf'],
                 '${SOURCES[0]} ${SOURCES[1:]} ${TARGET}')

# EOF
