# -*- Mode: Python -*-

import nul

Import('target_env')
Import('host_env')

nul.App(target_env, 'rocknshine',
        SOURCES = [ 'rocknshine.cc' ],
        INCLUDE = [ 'sigma0' ],
        LIBS    = [ 'tinf', 'vsys'])

host_env.Command('#bin/apps/rocknshine.example', ['pdfprepare.py', 'presentation.pdf'],
                 '${SOURCES[0]} ${SOURCES[1:]} ${TARGET}')

# EOF
