# -*- Mode: Python -*-

Import('output_dir')


prebuilt = [ 'coswig',
             'marburg',
             'munich',
             'santamonica',
             ]

Install(output_dir + '/boot', prebuilt)

# EOF
