# -*- Mode: Python -*-

import nul

Import('target_env')
nul.App(target_env, 'sigma0',
        SOURCES = Glob('*.cc'),
        LIBS    = [ 'runtime', 'hostvesa', 'host', 'service'],
        LINKSCRIPT = 'linker.ld',
        ROMFS   = [ 'cfg/admission.nulconfig', '#bin/apps/admission.nul' ],
        MEMSIZE = 2<<12) # enough memory for two stacks - echo and worker thread running on boot cpu

# Sigma0 binary is bloated. Install a gzipped version by default.
target_env.Command("#bin/apps/sigma0.nul.gz", "#bin/apps/sigma0.nul",
                   "gzip -n -c $SOURCE > $TARGET")

# EOF
