#!/usr/bin/env bash

_myexit() {
    code=$?
    cmd=$BASH_COMMAND
    echo >&2 "! $0 Command '$cmd' exit with code $code FAILED"
}

trap '_myexit' EXIT

set -e

mydir=$(readlink -f $(dirname $0))
. $mydir/wvtest.sh

WVPRINTCMD=yes

WVSTART "NOVA & NUL compilation (PASSIVE branch)"
cd ~/nul
WVPASS git submodule --quiet foreach --recursive 'git stash --quiet; git clean --quiet -fxd'
WVPASS git submodule --quiet update --init

cd build
CC=/home/sojka/gcc/gcc-4.6/bin/gcc
CXX=/home/sojka/gcc/gcc-4.6/bin/g++
export SCONSFLAGS="target_cc=$CC target_cxx=$CXX NO_TIMESTAMP=1 prepend_path=$HOME/bin"
WVPASS scons
WVPASS make -C ../alexb/apps/libvirt

cd ../alexb/apps/libvirt
wvnulrun ./libvirt-connect.wv $@ || :
wvnulrun ./libvirt-start-stop.wv $@ || :
wvnulrun ./libvirt-stat.wv $@ || :
wvnulrun ./libvirt-suspend-resume.wv $@ || :
wvnulrun ./libvirt.wv $@ || :
wvnulrun ./libvirt-xml.wv $@ || :

WVSTART "PASSIVE SVN checkout"
WVPASS cd $HOME/passive/src
WVPASS svn up
WVPASS svn status

WVSTART "PASSIVE compilation"
(set -x; mvn install) || : # Ignore errors here, we are only interested in resource manager
WVPASS true

WVSTART "Resource manager compilation"
WVPASS cd resmgr
WVPASS mvn compile

WVSTART "NOVA boot (PASSIVE configuration)"
. $(readlink -f $mydir/../../alexb/apps/libvirt/libvirt.wv.inc)
init
trap "finish" EXIT

WVSTART "Resource manager test"
#export LIBVIRT_DEBUG=1
WVPASS "mvn test -Dcon.string=nova+tls://$NOVA_IP:9999 -Dtest.domain=linux"
