#!/bin/bash

dir=$(dirname $0)
tests=$($dir/listtests)
exitcode=0
for file in $tests; do
    set -x
    cmd="$dir/wvnulrun $file $@"
    $cmd
    ret=$?
    set +x
    if [ "$ret" -ne 0 ]; then
	echo "! $0: '$cmd' returned non-zero exit code ($ret)  FAILED";
	exitcode=1
	if test "$WVTEST_BACKUP_FAILED" && file $file|grep -q "novaboot script"; then
	    backup="$WVTEST_BACKUP_FAILED/$(basename $file)"
	    mkdir -p $backup
	    $file --server=$backup | grep -v '^Testing ".*" in .*:$'
	    cp $file $backup
	    echo "exec \$(dirname \$0)/$(basename $file) --build-dir=\$(dirname \$0) \"\$@\"" > $backup/run
	    chmod +x $backup/run

	    echo
	    echo "Binaries of this failed test were backed up to $backup/"
	fi
    fi
done
exit $exitcode
