# -*- Mode: Python -*-

Import('target_env')

target_env.Link('#bin/apps/gt.nova',
                [ 'gt.cc',
                  ],
                LIBS=['runtime'],
                linkscript="linker.ld")

# EOF
