# -*- Mode: Python -*-

Import('output_dir')
Import('target_env')

target_env.Link(output_dir + '/apps/gt.nova',
                [ 'gt.cc',
                  ],
                LIBS=['runtime'],
                linkscript="linker.ld")

# EOF
