/*
 Highcharts Stock v1.0 Beta (2011-07-05)
 Exporting module

 (c) 2010-2011 Torstein H?nsi

 License: www.highcharts.com/license
*/
(function(){var i=Highcharts,y=i.Chart,C=i.addEvent,r=i.createElement,z=i.discardElement,u=i.css,w=i.merge,q=i.each,s=i.extend,D=Math.max,n=document,E=window,A="ontouchstart"in n.documentElement,B=i.setOptions({lang:{downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",exportButtonTitle:"Export to raster or vector image",printButtonTitle:"Print the chart"}});B.navigation={menuStyle:{border:"1px solid #A0A0A0",
background:"#FFFFFF"},menuItemStyle:{padding:"0 5px",background:"none",color:"#303030",fontSize:A?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{align:"right",backgroundColor:{linearGradient:[0,0,0,20],stops:[[0.4,"#F7F7F7"],[0.6,"#E3E3E3"]]},borderColor:"#B0B0B0",borderRadius:3,borderWidth:1,height:20,hoverBorderColor:"#909090",hoverSymbolFill:"#81A7CF",hoverSymbolStroke:"#4572A5",symbolFill:"#E0E0E0",symbolStroke:"#A0A0A0",symbolX:11.5,symbolY:10.5,verticalAlign:"top",
width:24,y:10}};B.exporting={type:"image/png",url:"http://export.highcharts.com/",width:800,buttons:{exportButton:{symbol:"exportIcon",x:-10,symbolFill:"#A8BF77",hoverSymbolFill:"#768F3E",_titleKey:"exportButtonTitle",menuItems:[{textKey:"downloadPNG",onclick:function(){this.exportChart()}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},{textKey:"downloadSVG",onclick:function(){this.exportChart({type:"image/svg+xml"})}},
{text:"View SVG",onclick:function(){var b=this.getSVG().replace(/</g,"\n&lt;").replace(/>/g,"&gt;");n.body.innerHTML="<pre>"+b+"</pre>"}}]},printButton:{symbol:"printIcon",x:-36,symbolFill:"#B5C9DF",hoverSymbolFill:"#779ABF",_titleKey:"printButtonTitle",onclick:function(){this.print()}}}};s(y.prototype,{getSVG:function(b){var c=this,a,f,d,g=w(c.options,b);if(!n.createElementNS)n.createElementNS=function(e,h){var j=n.createElement(h);j.getBBox=function(){return i.Renderer.prototype.Element.prototype.getBBox.apply({element:j})};
return j};b=r("div",null,{position:"absolute",top:"-9999em",width:c.chartWidth+"px",height:c.chartHeight+"px"},n.body);s(g.chart,{renderTo:b,forExport:true});g.exporting.enabled=false;g.chart.plotBackgroundImage=null;g.series=[];q(c.series,function(e){d=e.options;d.animation=false;d.showCheckbox=false;d.visible=e.visible;if(d&&d.marker&&/^url\(/.test(d.marker.symbol))d.marker.symbol="circle";g.series.push(d)});a=new Highcharts.Chart(g);q(["xAxis","yAxis"],function(e){q(c[e],function(h,j){var o=a[e][j],
k=h.getExtremes(),m=k.userMin;k=k.userMax;if(m!==undefined||k!==undefined)o.setExtremes(m,k,true,false)})});f=a.container.innerHTML;g=null;a.destroy();z(b);f=f.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/isTracker="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" ]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,
function(e){return e.toLowerCase()});f=f.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'");if(f.match(/ xmlns="/g).length==2)f=f.replace(/xmlns="[^"]+"/,"");return f},exportChart:function(b,c){var a,f=this.getSVG(c);b=w(this.options.exporting,b);a=r("form",{method:"post",action:b.url},{display:"none"},n.body);q(["filename","type","width","svg"],function(d){r("input",{type:"hidden",name:d,value:{filename:b.filename||"chart",type:b.type,width:b.width,svg:f}[d]},null,a)});a.submit();
z(a)},print:function(){var b=this,c=b.container,a=[],f=c.parentNode,d=n.body,g=d.childNodes;if(!b.isPrinting){b.isPrinting=true;q(g,function(e,h){if(e.nodeType==1){a[h]=e.style.display;e.style.display="none"}});d.appendChild(c);E.print();setTimeout(function(){f.appendChild(c);q(g,function(e,h){if(e.nodeType==1)e.style.display=a[h]});b.isPrinting=false},1E3)}},contextMenu:function(b,c,a,f,d,g){var e=this,h=e.options.navigation,j=h.menuItemStyle,o=e.chartWidth,k=e.chartHeight,m="cache-"+b,l=e[m],p=
D(d,g),t,x;if(!l){e[m]=l=r("div",{className:"highcharts-"+b},{position:"absolute",zIndex:1E3,padding:p+"px"},e.container);t=r("div",null,s({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},h.menuStyle),l);x=function(){u(l,{display:"none"})};C(l,"mouseleave",x);q(c,function(v){if(v)r("div",{onmouseover:function(){u(this,h.menuItemHoverStyle)},onmouseout:function(){u(this,j)},innerHTML:v.text||i.getOptions().lang[v.textKey]},s({cursor:"pointer"},j),
t)[A?"ontouchstart":"onclick"]=function(){x();v.onclick.apply(e,arguments)}});e.exportMenuWidth=l.offsetWidth;e.exportMenuHeight=l.offsetHeight}b={display:"block"};if(a+e.exportMenuWidth>o)b.right=o-a-d-p+"px";else b.left=a-p+"px";if(f+g+e.exportMenuHeight>k)b.bottom=k-f-p+"px";else b.top=f+g-p+"px";u(l,b)},addButton:function(b){function c(){k.attr(p);o.attr(l)}var a=this,f=a.renderer,d=w(a.options.navigation.buttonOptions,b),g=d.onclick,e=d.menuItems,h=d.width,j=d.height,o,k,m;b=d.borderWidth;var l=
{stroke:d.borderColor},p={stroke:d.symbolStroke,fill:d.symbolFill};if(d.enabled!==false){o=f.rect(0,0,h,j,d.borderRadius,b).align(d,true).attr(s({fill:d.backgroundColor,"stroke-width":b,zIndex:19},l)).add();m=f.rect(0,0,h,j,0).align(d).attr({fill:"rgba(255, 255, 255, 0.001)",title:i.getOptions().lang[d._titleKey],zIndex:21}).css({cursor:"pointer"}).on("mouseover",function(){k.attr({stroke:d.hoverSymbolStroke,fill:d.hoverSymbolFill});o.attr({stroke:d.hoverBorderColor})}).on("mouseout",c).on("click",
c).add();if(e)g=function(){c();var t=m.getBBox();a.contextMenu("export-menu",e,t.x,t.y,h,j)};m.on("click",function(){g.apply(a,arguments)});k=f.symbol(d.symbol,d.symbolX,d.symbolY,(d.symbolSize||12)/2).align(d,true).attr(s(p,{"stroke-width":d.symbolStrokeWidth||1,zIndex:20})).add()}}});i.Renderer.prototype.symbols.exportIcon=function(b,c,a){return["M",b-a,c+a,"L",b+a,c+a,b+a,c+a*0.5,b-a,c+a*0.5,"Z","M",b,c+a*0.5,"L",b-a*0.5,c-a/3,b-a/6,c-a/3,b-a/6,c-a,b+a/6,c-a,b+a/6,c-a/3,b+a*0.5,c-a/3,"Z"]};i.Renderer.prototype.symbols.printIcon=
function(b,c,a){return["M",b-a,c+a*0.5,"L",b+a,c+a*0.5,b+a,c-a/3,b-a,c-a/3,"Z","M",b-a*0.5,c-a/3,"L",b-a*0.5,c-a,b+a*0.5,c-a,b+a*0.5,c-a/3,"Z","M",b-a*0.5,c+a*0.5,"L",b-a*0.75,c+a,b+a*0.75,c+a,b+a*0.5,c+a*0.5,"Z"]};y.prototype.callbacks.push(function(b){var c,a=b.options.exporting,f=a.buttons;if(a.enabled!==false)for(c in f)b.addButton(f[c])})})();
