/*
 Highstock JS v1.1.3 (2012-02-03)
 Exporting module

 (c) 2010-2011 Torstein H?nsi

 License: www.highcharts.com/license
*/
(function(){var f=Highcharts,w=f.Chart,x=f.addEvent,z=f.removeEvent,r=f.createElement,t=f.discardElement,s=f.css,l=f.merge,k=f.each,n=f.extend,A=Math.max,h=document,B=window,y=h.documentElement.ontouchstart!==void 0,u=f.getOptions();n(u.lang,{downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",exportButtonTitle:"Export to raster or vector image",printButtonTitle:"Print the chart"});u.navigation={menuStyle:{border:"1px solid #A0A0A0",
background:"#FFFFFF"},menuItemStyle:{padding:"0 5px",background:"none",color:"#303030",fontSize:y?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{align:"right",backgroundColor:{linearGradient:[0,0,0,20],stops:[[0.4,"#F7F7F7"],[0.6,"#E3E3E3"]]},borderColor:"#B0B0B0",borderRadius:3,borderWidth:1,height:20,hoverBorderColor:"#909090",hoverSymbolFill:"#81A7CF",hoverSymbolStroke:"#4572A5",symbolFill:"#E0E0E0",symbolStroke:"#A0A0A0",symbolX:11.5,symbolY:10.5,verticalAlign:"top",
width:24,y:10}};u.exporting={type:"image/png",url:"http://export.highcharts.com/",width:800,buttons:{exportButton:{symbol:"exportIcon",x:-10,symbolFill:"#A8BF77",hoverSymbolFill:"#768F3E",_id:"exportButton",_titleKey:"exportButtonTitle",menuItems:[{textKey:"downloadPNG",onclick:function(){this.exportChart()}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},{textKey:"downloadSVG",
onclick:function(){this.exportChart({type:"image/svg+xml"})}}]},printButton:{symbol:"printIcon",x:-36,symbolFill:"#B5C9DF",hoverSymbolFill:"#779ABF",_id:"printButton",_titleKey:"printButtonTitle",onclick:function(){this.print()}}}};n(w.prototype,{getSVG:function(a){var c=this,b,e,d,g=l(c.options,a);if(!h.createElementNS)h.createElementNS=function(b,a){var c=h.createElement(a);c.getBBox=function(){return f.Renderer.prototype.Element.prototype.getBBox.apply({element:c})};return c};a=r("div",null,{position:"absolute",
top:"-9999em",width:c.chartWidth+"px",height:c.chartHeight+"px"},h.body);n(g.chart,{renderTo:a,forExport:!0});g.exporting.enabled=!1;g.chart.plotBackgroundImage=null;g.series=[];k(c.series,function(b){d=l(b.options,{animation:!1,showCheckbox:!1,visible:b.visible});if(!d.isInternal){if(d&&d.marker&&/^url\(/.test(d.marker.symbol))d.marker.symbol="circle";g.series.push(d)}});b=new Highcharts.Chart(g);k(["xAxis","yAxis"],function(a){k(c[a],function(c,d){var e=b[a][d],g=c.getExtremes(),f=g.userMin,g=g.userMax;
(f!==void 0||g!==void 0)&&e.setExtremes(f,g,!0,!1)})});e=b.container.innerHTML;g=null;b.destroy();t(a);e=e.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/isTracker="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad").replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" ]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,
function(b){return b.toLowerCase()});e=e.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'");e.match(/ xmlns="/g).length===2&&(e=e.replace(/xmlns="[^"]+"/,""));return e},exportChart:function(a,c){var b,e=this.getSVG(l(this.options.exporting.chartOptions,c)),a=l(this.options.exporting,a);b=r("form",{method:"post",action:a.url},{display:"none"},h.body);k(["filename","type","width","svg"],function(c){r("input",{type:"hidden",name:c,value:{filename:a.filename||"chart",type:a.type,
width:a.width,svg:e}[c]},null,b)});b.submit();t(b)},print:function(){var a=this,c=a.container,b=[],e=c.parentNode,d=h.body,g=d.childNodes;if(!a.isPrinting)a.isPrinting=!0,k(g,function(a,c){if(a.nodeType===1)b[c]=a.style.display,a.style.display="none"}),d.appendChild(c),B.print(),setTimeout(function(){e.appendChild(c);k(g,function(a,c){if(a.nodeType===1)a.style.display=b[c]});a.isPrinting=!1},1E3)},contextMenu:function(a,c,b,e,d,g){var i=this,f=i.options.navigation,h=f.menuItemStyle,o=i.chartWidth,
p=i.chartHeight,q="cache-"+a,j=i[q],m=A(d,g),v,l;if(!j)i[q]=j=r("div",{className:"highcharts-"+a},{position:"absolute",zIndex:1E3,padding:m+"px"},i.container),v=r("div",null,n({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},f.menuStyle),j),l=function(){s(j,{display:"none"})},x(j,"mouseleave",l),k(c,function(a){if(a){var b=r("div",{onmouseover:function(){s(this,f.menuItemHoverStyle)},onmouseout:function(){s(this,h)},innerHTML:a.text||i.options.lang[a.textKey]},
n({cursor:"pointer"},h),v);b[y?"ontouchstart":"onclick"]=function(){l();a.onclick.apply(i,arguments)};i.exportDivElements.push(b)}}),i.exportDivElements.push(v,j),i.exportMenuWidth=j.offsetWidth,i.exportMenuHeight=j.offsetHeight;a={display:"block"};b+i.exportMenuWidth>o?a.right=o-b-d-m+"px":a.left=b-m+"px";e+g+i.exportMenuHeight>p?a.bottom=p-e-m+"px":a.top=e+g-m+"px";s(j,a)},addButton:function(a){function c(){p.attr(m);o.attr(j)}var b=this,e=b.renderer,d=l(b.options.navigation.buttonOptions,a),g=
d.onclick,f=d.menuItems,h=d.width,k=d.height,o,p,q,a=d.borderWidth,j={stroke:d.borderColor},m={stroke:d.symbolStroke,fill:d.symbolFill};if(!b.exportDivElements)b.exportDivElements=[],b.exportSVGElements=[];d.enabled!==!1&&(o=e.rect(0,0,h,k,d.borderRadius,a).align(d,!0).attr(n({fill:d.backgroundColor,"stroke-width":a,zIndex:19},j)).add(),q=e.rect(0,0,h,k,0).align(d).attr({id:d._id,fill:"rgba(255, 255, 255, 0.001)",title:b.options.lang[d._titleKey],zIndex:21}).css({cursor:"pointer"}).on("mouseover",
function(){p.attr({stroke:d.hoverSymbolStroke,fill:d.hoverSymbolFill});o.attr({stroke:d.hoverBorderColor})}).on("mouseout",c).on("click",c).add(),f&&(g=function(){c();var a=q.getBBox();b.contextMenu("export-menu",f,a.x,a.y,h,k)}),q.on("click",function(){g.apply(b,arguments)}),p=e.symbol(d.symbol,d.symbolX,d.symbolY,(d.symbolSize||12)/2).align(d,!0).attr(n(m,{"stroke-width":d.symbolStrokeWidth||1,zIndex:20})).add(),b.exportSVGElements.push(o,q,p))},destroyExport:function(){var a,c;for(a=0;a<this.exportSVGElements.length;a++)c=
this.exportSVGElements[a],c.onclick=c.ontouchstart=null,this.exportSVGElements[a]=c.destroy();for(a=0;a<this.exportDivElements.length;a++)c=this.exportDivElements[a],z(c,"mouseleave"),this.exportDivElements[a]=c.onmouseout=c.onmouseover=c.ontouchstart=c.onclick=null,t(c)}});f.Renderer.prototype.symbols.exportIcon=function(a,c,b){return["M",a-b,c+b,"L",a+b,c+b,a+b,c+b*0.5,a-b,c+b*0.5,"Z","M",a,c+b*0.5,"L",a-b*0.5,c-b/3,a-b/6,c-b/3,a-b/6,c-b,a+b/6,c-b,a+b/6,c-b/3,a+b*0.5,c-b/3,"Z"]};f.Renderer.prototype.symbols.printIcon=
function(a,c,b){return["M",a-b,c+b*0.5,"L",a+b,c+b*0.5,a+b,c-b/3,a-b,c-b/3,"Z","M",a-b*0.5,c-b/3,"L",a-b*0.5,c-b,a+b*0.5,c-b,a+b*0.5,c-b/3,"Z","M",a-b*0.5,c+b*0.5,"L",a-b*0.75,c+b,a+b*0.75,c+b,a+b*0.5,c+b*0.5,"Z"]};w.prototype.callbacks.push(function(a){var c,b=a.options.exporting,e=b.buttons;if(b.enabled!==!1){for(c in e)a.addButton(e[c]);x(a,"destroy",a.destroyExport)}})})();
