# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'forth',
        SOURCES = [ 'forth.cc' ],
        LIBS    = [ 'ficl', 'service', 'crun', 'longjmp' ],
        MEMSIZE = 1<<19)

# EOF
