# -*- Mode: Python -*-

import nul
Import('target_env')

# sources are based on matrixssl-3-2-2-open release from 7th October 2011

target_env.Append(CPPPATH = [ 'own/include',
                              'contrib',
                              'contrib/core',
                              'contrib/crypto',
                              'contrib/matrixssl']);

nul.Lib(target_env, 'ssl_matrix',
        SOURCES = [Glob('contrib/core/*.c'),
                   Glob('contrib/crypto/*/*.c'),
                   Glob('contrib/matrixssl/*.c'),
                   'own/sys.cc'
                   ])
