# -*- Mode: Python -*-

Import('output_dir')
Import('target_env')

target_env.Link(output_dir + '/apps/example.nova',
                [ File('example.cc')
                  ],
                linkscript="example.ld")

# EOF
