# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env,
        "example",
        SOURCES = [ 'main.c' ],
        # LIBS defaults to ['nova']
        LIBS = ['string', 'nova'],
        # LINKSCRIPT defaults to example.ld
        LINKSCRIPT = 'roottask.ld')

# EOF
