# -*- Mode: Python -*-

Import('output_dir')
Import('target_env')

target_env.Link(output_dir + '/apps/example.nova',
                [ 'start.S',
                  'main.c',
                  
                  ],
                linkscript="roottask.ld")

# EOF
