# -*- Mode: Python -*-

import nul

Import('target_env')

obj_env = nul.LibEnv(target_env, ['runtime', 'string', 'nova'])
for f in Glob('*.cc'):
    obj_env.Object(f)

nul.Lib(target_env,
        'models',
        SOURCES = [ 
        # Generic IO and memory
        'aliases',
        'directio',
        'nullio',
        'memorycontroller',
        
        # Keyboard, mouse, serial
        'keyboardcontroller',
        'ps2keyboard',
        'ps2mouse',
        'serial16550',
        'serial2kbd',
        'kbd2serial',

        # PIT, PIC, Sysctrl, RTC
        'pic8259',
        'pit8254',
        'sysctrlport',
        'rtc146818',

        # PCI
        'pcihostbridge',
        'satadrive',

        # VGA
        'vga',

        ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])


# EOF
