# -*- Mode: Python -*-

import nul

Import('target_env')
Import('host_env')

nul.App(target_env, 'novatop',
        SOURCES = [ 'novatop.cc' ],
        INCLUDE = [ 'sigma0' ],
        LIBS    = [ 'service',
                    # 64-bit division
                    'crun' ])

# EOF
