# -*- Mode: Python -*-

import nul

Import('target_env')

obj_env = nul.LibEnv(target_env, ['runtime', 'string', 'nova'])
for f in Glob('*.cc'):
    obj_env.Object(f)


nul.Lib(target_env,
        'executors',
        SOURCES = [
        'cpuidexecutor',
        'msrexecutor',
        'triplefaultexecutor',
        'irqexecutor',
        'initexecutor',
        'novahalifax',
        'virtualbios',
        'vesabios',
        'multiboot',
        ],
        INCLUDE = [ 'sigma0' ],
        LIBS = [ 'runtime', 'string', 'nova' ])

# EOF
