# -*- Mode: Python -*-

Import('target_env')

target_env.StaticLibrary('#bin/lib/tinf',
                         [
        'src/tinflate.c',
        'src/tinfgzip.c',
        'src/tinfzlib.c',
        'src/adler32.c',
        'src/crc32.c',
        ])

# EOF
