# -*- Mode: Python -*-

Import('target_env')

target_env.StaticLibrary('#bin/lib/runtime',
                         [
        'asm.S',
        'logging.cc',
        'simplemalloc.cc',
        'vprintf.cc',
        ])

# EOF
