# -*- Mode: Python -*-

import nul

Import('target_env')

Command('softcore.c', ['softwords/softcore.awk',
                       'softwords/softcore.fr',
                       'softwords/jhlocal.fr',
                       'softwords/marker.fr',
                       'softwords/freebsd.fr',
                       'softwords/ficllocal.fr',
                       'softwords/ifbrack.fr',
                       'softwords/prefix.fr',
                       'softwords/oo.fr',
                       'softwords/classes.fr',
                       ],
        """cat ${SOURCES[1:]} | awk -f $SOURCE -v datestamp="`LC_ALL=C date`" > $TARGET""")

ficl_env = target_env.Clone()
# This removes an expensive call from most standard words, but makes
# even simple errors fatal. Disabled for now.
# ficl_env.Append(CPPFLAGS = ["-DFICL_ROBUST=0"])

nul.Lib(ficl_env, "ficl",
        LIBS = ['longjmp', 'crun', 'string' ],
        SOURCES = ['dict.c',
                   'ficl.c',
                   'float.c',
                   'loader.c',
                   'math64.c',
                   'nova.cc',
                   'prefix.c',
                   'search.c',
                   'stack.c',
                   'softcore.c',
                   'tools.c',
                   'vm.c',
                   'words.c',
                   'i386-sysdep.c',
                   ])

# EOF
