# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'gt',
        SOURCES = [ 'gt.cc' ],
        INCLUDE = [ 'sigma0' ],
        LIBS    = [ 'vsys', 'string' ],
        LINKSCRIPT = 'linker.ld')

# EOF
