# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'gt',
        SOURCES = [ 'gt.cc' ],
        OBJS    = [ '#service/simplemalloc.o', '#service/logging.o', '#service/vprintf.o'])

# EOF
