# -*- Mode: Python -*-

import nul

Import('target_env')
Import('output_dir')

nul.Lib(target_env, output_dir,
        "nova",
        SOURCES = [ 'start.S',
                    'reply.S',
                    ]) 

# EOF
