# -*- Mode: Python -*-

import nul

Import('target_env')

nul.Lib(target_env,
        "nova",
        SOURCES = [ 'start.S',
                    'reply.S',
                    'utcb.c',
                    ]) 

# EOF
