# -*- Mode: Python -*-

prebuilt = [ 'coswig',
             'marburg',
             'munich',
             'santamonica',
             'vilo', 
             'bender',
             ]

Install('#bin/boot', prebuilt)

# EOF
