# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'cycleburner',
        SOURCES = [ 'cycleburner.cc'],
        INCLUDE = [ 'sigma0' ],
        OBJS    = [ '#service/simplemalloc.o',
                    '#service/logging.o',
                    '#service/vprintf.o',
                    ],
        LIBS    = [ 'dlmalloc', 'runtime' ],
        MEMSIZE = 1<<20)

# EOF
