# -*- Mode: Python -*-

import nul

Import('target_env')

nul.App(target_env, 'test_ip',
        SOURCES = [ 'main.cc' ],
        INCLUDE = [ 'sigma0' ],
        OBJS    = [ '#service/simplemalloc.o', '#service/logging.o', '#service/vprintf.o'],
        LIBS    = [ 'ip_lwip', 'runtime' ],
        MEMSIZE = 2<<20)

# EOF
