# -*- Mode: Python -*-

Import('initrd32_works')
Import('initrd32_env')

if initrd32_works:
    Install("#bin/host",
            initrd32_env.Program('tap_connector',
                                 ["tap_connector.cc"]))
else:
    print("Skip building tap_connector.")

# EOF
