# -*- Mode: Python -*-

Import('target_env')
Import('output_dir')

target_env.StaticLibrary(output_dir + "/lib/sys",
                         [
                           'start.S',
                           'reply.S',
                           ])

# EOF
