# -*- Mode: Python -*-

import nul

Import('target_env')

root_env = target_env.Clone()

def bin_to_c(target, source, env):
    inf = open(str(source[0]), 'rb')
    outf = open(str(target[0]), 'wb')
    b = [0]
    while True:
        c = inf.read(1)
        if not c:
            break
        outf.write(str(ord(c[0])) + ', ')
    outf.close()
    inf.close()

root_env['BUILDERS']['BinToC'] = Builder(action = bin_to_c,
                                         suffic = '.inc')

root_env.BinToC('main.inc', 'main.4th'),
root_env.Append(CPPPATH = ["."])
nul.App(root_env, 'root4th',
       SOURCES = [ 'root4th.c',
                   'start.S',
                   ],
       LIBS = [ 'ficl', 'crun', 'longjmp' ],
       LINKSCRIPT = 'root4th.ld')


# EOF
